/* f54 — four reports, and the rule under the first one
   ============================================================
   1. HATI'S MARKS BELONG ONLY ON WHAT HATI EXECUTED. A contract signed on
      paper, or in somebody else's system, and then filed here was not signed by
      us. Printing it must give back what was filed — adding a seal, a
      fingerprint or an audit trail to somebody else's executed contract is HaTi
      asserting a part in an act it had no part in. I built the print block last
      round and got this wrong: it rendered an "ON FILE / MIGRATED" variant for
      exactly the documents that should carry nothing.

   2. THE PANEL ASKED QUESTIONS ON THE READER'S BEHALF. Three rotating chips,
      put there by the product. What to ask is the reader's to decide.

   3. "ADD A CLAUSE" IS GONE. Proposing a clause the contract does not have is a
      real act, but it was two blank prompt boxes with no sight of the document.

   4. THE DOC PAGE FOLDS. Nine actions, a status strip and a tab row before one
      line of the contract — right while deciding, in the way while reading. */
const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const { buildWorld } = require('./world');
const { buildPortal } = require('./portalworld');
const F = require('./clausefixtures.js');

function contract(over = {}){
  return { id: 'MK-189', name: 'Warehousing Services Agreement',
    counterparty: 'Juno Limited', template: 'WH', status: 'Under Review',
    folder: 'proc', fields: {}, metadata: {}, audit: [], rounds: [], versions: [],
    signatures: [], comments: [], redlineText: F.protoRich(), format: 'rich', ...over };
}

/* ============================================================
   1 — whose signature was it?
   ============================================================ */
describe('a printed contract carries HaTi marks only where HaTi signed it', () => {
  /* `opts` reaches exportPDF's second argument. There are two exports now: the
     default is the copy that leaves the building, and {record:true} is the copy
     you keep. The rule this file is about — HaTi marks only where HaTi signed —
     still governs both; the record copy is where those marks are allowed to
     appear at all, not a licence to add them to somebody else's contract. */
  function printed(over, opts){
    const p = buildPortal();
    p.win.print = () => {}; p.win.persist = () => {}; p.win.renderAuditSection = () => {};
    const c = p.win.migrateContract(contract(over));
    p.win.exportPDF(c, opts);
    const root = p.win.document.getElementById('print-root');
    return { win: p.win, c, html: root.innerHTML, text: root.textContent.replace(/\s+/g, ' ') };
  }
  const SIGNED_HERE = { status:'Signed', signedAt:'27 Jul 2026, 16:30',
    hash:'1c71d57e9298790d100811f4108f3e2332562ad17e24401c2509fe7ef660cebb',
    execution:{ textHash:'abc123' },
    audit:[{ at:'2026-07-27T16:30:00Z', user:'Young Mbagaya', action:'Signed', detail:'Executed' }],
    signatures:[{ party:'first', name:'Young Mbagaya', email:'y@m.com', form:'type', at:'2026-07-27T16:30:00Z' }] };
  /* A migrated record: signed elsewhere, filed here. hash === 'MIGRATED' is the
     app's own marker for it. */
  const MIGRATED = { ...SIGNED_HERE, hash:'MIGRATED', signatures:[],
    migration:{ executedOutside:true, importedBy:'Young Mbagaya' },
    source:'upload', redlineText:null, format:'text',
    upload:{ fileName:'36C25520Q0076-013.pdf', fileHash:'f976e519',
      extractedText:'AGREEMENT\nClause 1 · Scope\nThe supplier shall deliver.' } };

  test('signed in HaTi — the seal and the signatures print on the copy you send', () => {
    const r = printed(SIGNED_HERE);
    assert.match(r.text, /Executed & Sealed/, 'the execution IS the contract, not a HaTi mark');
    assert.match(r.text, /Young Mbagaya/, 'and so is who signed it');
  });

  test('…but the audit trail does not — that copy goes to a counterparty', () => {
    /* The distribution copy is the agreement, the signatures and the customer's
       own letterhead. HaTi's account of how the file was handled is ours, not
       theirs, and nobody wants their software's logbook stapled to a contract
       they are sending out. */
    const r = printed(SIGNED_HERE);
    assert.ok(!/Audit trail/.test(r.text), 'no logbook on the copy that leaves the building');
    assert.ok(!/Contract Lifecycle/.test(r.text), 'and no HaTi masthead above the customer’s branding');
    assert.ok(!/Generated by HaTi CLM/.test(r.text), 'nor a HaTi footer under their contract');
  });

  test('the record copy keeps everything, because that is the copy you file', () => {
    const r = printed(SIGNED_HERE, { record: true });
    assert.match(r.text, /Executed & Sealed/);
    assert.match(r.text, /Audit trail/, 'the evidence still exists — it just is not distributed');
    assert.match(r.text, /Generated by HaTi CLM/);
  });

  test('the record copy still may not stamp a contract HaTi did not execute', () => {
    /* The important half of the rule: asking for the full record does not turn
       HaTi into a party to somebody else's signing. A migrated contract gets
       nothing of ours on either copy. */
    const r = printed(MIGRATED, { record: true });
    assert.ok(!/Executed & Sealed/.test(r.text), 'we did not execute it, whatever was asked for');
    assert.ok(!/Audit trail/.test(r.text), 'our handling record is not their contract’s provenance');
  });

  test('executed OUTSIDE HaTi — no seal roundel, no execution block', () => {
    const r = printed(MIGRATED);
    assert.ok(!/Executed & Sealed/.test(r.text), 'we did not execute it');
    assert.ok(!/Executed outside HaTi/.test(r.text),
      'nor may we stamp it with our account of somebody else\'s signing');
    assert.ok(!/ON FILE|MIGRATED/.test(r.text), 'and no roundel of our own');
  });

  test('and no fingerprint, no audit trail — nothing of ours added at all', () => {
    const r = printed(MIGRATED);
    assert.ok(!/DOCUMENT SEAL|FILE FINGERPRINT/i.test(r.text), 'got: ' + r.text.slice(0, 300));
    assert.ok(!/Audit trail/.test(r.text), 'our record of handling it is not part of their contract');
  });

  test('what does print is the wording it was filed with', () => {
    const r = printed(MIGRATED);
    assert.match(r.text, /The supplier shall deliver/);
  });

  test('an uploaded document nobody signed prints as the document', () => {
    const r = printed({ source:'upload', redlineText:null, format:'text',
      upload:{ fileName:'x.pdf', fileHash:'aa',
        extractedText:'AGREEMENT\nClause 1 · Scope\nThe supplier shall deliver.' } });
    assert.match(r.text, /The supplier shall deliver/);
    assert.ok(!/File fingerprint|signing certificate/i.test(r.text),
      'the certificate card is HaTi filing metadata, not part of their agreement');
    assert.ok(!/Executed & Sealed/.test(r.text));
  });

  test('the rule is one predicate, so nothing can disagree with it', () => {
    const w = buildPortal().win;
    assert.equal(w.printIsHatiExecuted(w.migrateContract(contract(SIGNED_HERE))), true);
    assert.equal(w.printIsHatiExecuted(w.migrateContract(contract(MIGRATED))), false);
    assert.equal(w.printIsHatiExecuted(w.migrateContract(contract())), false, 'unsigned');
    assert.equal(w.printIsHatiExecuted(w.migrateContract(contract({ status:'Signed' }))), false,
      'signed with no signature on record is not a signature we took');
  });
});

/* ============================================================
   2 — the panel does not ask questions for you
   ============================================================ */
describe('Copilot opens without prompting', () => {
  test('no suggestion chips are rendered', () => {
    const { win } = buildWorld({});
    const el = win.document.createElement('div');
    el.id = 'ai-suggest';
    win.document.body.appendChild(el);
    if (typeof win.renderAISuggest !== 'function') return;   // ai.js not on this stage
    win.renderAISuggest();
    assert.equal(el.innerHTML.trim(), '', 'what to ask is the reader\'s to decide');
  });
});

/* ============================================================
   3 — Add a clause is gone
   ============================================================ */
describe('the clause tools are Edit and Delete', () => {
  async function room(){
    const { win } = buildWorld({ negotiationView: true });
    const c = contract();
    win.negoInit(c);
    win.openNegotiationRoom(c, { side:'owner', by:'Wanjiru Kamau', persist:false });
    return win.document;
  }
  test('no trigger, and no dialog behind it', async () => {
    const d = await room();
    assert.equal(d.querySelector('[data-nego-add-after]'), null);
    assert.ok(!/Add a clause/.test(d.body.innerHTML));
  });
  test('but editing and deleting a clause both survive', async () => {
    const d = await room();
    assert.ok(d.querySelector('[data-nego-edit]'), 'wording is still proposable');
    assert.equal(d.querySelector('[data-nego-del]'), null,
      'Propose deletion was removed from both seats');
  });
});

/* ============================================================
   4 — the Doc page folds
   ============================================================ */
describe('the contract header collapses', () => {
  function page(){
    const { win } = buildWorld({ contractView: true });
    /* core.js is not on this stage, and lsGet/lsSet live there. Stood in for,
       exactly as world.js stands in for persist() — what is under test is what
       applyWsCollapse DECIDES, not where the choice is kept. */
    let store = {};
    win.lsGet = k => store[k];
    win.lsSet = (k, v) => { store[k] = v; };
    const doc = win.document;
    doc.body.innerHTML = `
      <div data-ws-fold="actions"><button id="x">Share</button></div>
      <div style="display:flex;gap:6px"><button id="ws-new">Draft new agreement</button>
        <button id="ws-collapse" aria-expanded="true"></button></div>
      <div id="ws-actionbar" data-ws-fold="strip">Drafting</div>`;
    return { win, doc };
  }
  test('folding hides the action rows and leaves the rest', () => {
    const { win, doc } = page();
    win.lsSet(win.WS_FOLD_KEY(), true);
    win.applyWsCollapse();
    for (const el of doc.querySelectorAll('[data-ws-fold]'))
      assert.equal(el.style.display, 'none');
    /* Whatever sits in that slot stays. It was Ask Copilot; it is now Draft
       new agreement (see f91). What is under test is that applyWsCollapse
       folds only what carries data-ws-fold and leaves the row beside it
       alone — the identity of the button in it is not this file's business. */
    assert.notEqual(doc.getElementById('ws-new').style.display, 'none',
      'the action outside the folding rows stays');
  });

  test('the control that folds it is not inside what it folds', () => {
    const { doc } = page();
    const btn = doc.getElementById('ws-collapse');
    assert.equal(btn.closest('[data-ws-fold]'), null,
      'a control that hides itself cannot be pressed again');
  });

  test('unfolding puts everything back, and the button says which way it goes', () => {
    const { win, doc } = page();
    win.lsSet(win.WS_FOLD_KEY(), true); win.applyWsCollapse();
    assert.equal(doc.getElementById('ws-collapse').getAttribute('aria-expanded'), 'false');
    win.lsSet(win.WS_FOLD_KEY(), false); win.applyWsCollapse();
    for (const el of doc.querySelectorAll('[data-ws-fold]'))
      assert.notEqual(el.style.display, 'none');
    assert.equal(doc.getElementById('ws-collapse').getAttribute('aria-expanded'), 'true');
  });

  test('the choice is remembered per user, not per contract', () => {
    const { win } = buildWorld({ contractView: true });
    assert.match(win.WS_FOLD_KEY(), /^hati\.v1\.wsChrome\./);
    assert.ok(!/MK-/.test(win.WS_FOLD_KEY()),
      'someone who reads more than they act wants it folded on every contract');
  });
});

/* ============================================================
   5 — a version is something a person took and named
   ============================================================
   Snapshots fired on anything that touched the wording, and each landed in the
   version list named after the EVENT that triggered it rather than after what
   changed: "#CHG-001 accepted — Clause 4", "Shared for review", "Round 1 —
   sent to Juno Limited". Bookkeeping presented as document history, none of it
   anything a person would choose to compare against.

   A version is now what somebody took and NAMED. The copies the system still
   needs are kept, unlisted — and they must be, because two things depend on
   them: the copy before a first edit is the only record of the original
   wording, and reviewing a returned redline diffs against the most recent copy
   when the response carries no base text of its own. */
describe('a version is named, and the bookkeeping is not a version', () => {
  const F2 = require('./clausefixtures.js');
  async function negotiated(){
    const { win } = buildWorld({ negotiationView: true });
    const c = contract();
    win.negoInit(c);
    const cl = win.negoClauseList(c).find(x => x.num === '4');
    const ch = await win.negoEditClause(c, cl.clauseId, `<p>${F2.PROTO_ASKS['4'].text}</p>`,
      { side: 'counterparty', author: 'Erik Lindqvist', summary: 'Net-45' });
    win.negoResolve(c, ch.id, 'accepted', { by: 'Wanjiru Kamau' });
    return { win, c };
  }

  test('deciding a change no longer files a version named after the change', async () => {
    const { win, c } = await negotiated();
    const labels = win.listedVersions(c).map(v => v.label);
    assert.ok(!labels.some(l => /^#CHG/.test(l)), 'got: ' + labels.join(' | '));
  });

  test('but the copy is still KEPT — the machinery depends on it', async () => {
    const { c } = await negotiated();
    assert.ok((c.versions || []).length >= 1,
      'the last copy is what a returned redline diffs against when it carries no base');
  });

  test('closing a round is listed, and takes the name with it', async () => {
    const { win, c } = await negotiated();
    win.negoAdvanceRound(c, { by: 'Wanjiru Kamau' });
    const labels = win.listedVersions(c).map(v => v.label);
    assert.deepEqual(Array.from(labels), ['Round 1 closed'],
      'the milestone, not the decision that happened to precede it');
  });

  /* Without this the milestone vanishes: a round closes moments after its last
     change was accepted, so the text is identical and the copy already stored
     is the unlisted per-change one. */
  test('a listed capture promotes an unlisted copy rather than being swallowed', async () => {
    const { win, c } = await negotiated();
    const before = (c.versions || []).length;
    assert.equal(c.versions[before - 1].listed, false, 'the per-change copy is not listed');
    win.negoAdvanceRound(c, { by: 'Wanjiru Kamau' });
    assert.equal((c.versions || []).length, before, 'no duplicate — the wording did not move');
    assert.equal(c.versions[before - 1].listed, true, 'the copy is promoted');
    assert.equal(c.versions[before - 1].label, 'Round 1 closed', 'and renamed to why it matters');
  });

  /* The milestone is kept — see the two tests above — and it is not OFFERED,
     because "Round 1 closed" and "Round 2 - Baseline" are the same document
     under two names. The selector asks which two documents to read side by
     side; the version history answers what happened and when.

     What DID change with f69 is that the round that closed brings its own
     starting wording onto the list. That is a third document, not a third name
     for the same one: it is what the contract said before round 1 moved it. */
  test('the compare dropdown offers the live pair, and not the same document twice', async () => {
    const { win, c } = await negotiated();
    win.negoAdvanceRound(c, { by: 'Wanjiru Kamau' });
    assert.deepEqual(Array.from(win.listedVersions(c).map(v => v.label)), ['Round 1 closed'],
      'the milestone is still on the record');
    const offered = win.negoVersionChoices(c);
    const labels = offered.map(o => o.label);
    assert.deepEqual(Array.from(labels),
      ['Round 1 - Baseline', 'Round 2 - Baseline', 'Round 2 - Working Version'],
      'the round that closed, the wording it produced, and what is on the table now');
    const doc = k => offered.find(o => o.key === k).text.replace(/\s+/g, ' ').trim();
    assert.notEqual(doc('round1-baseline'), doc('baseline'),
      'the round that closed started from different wording — that is why it is a row');
    /* The snapshot the close took says word for word what the new baseline
       says, so it is named once, and the name kept is the live one — the row
       you can always get back to. */
    assert.ok(!labels.some(l => /Round 1 - V/.test(l)),
      'and "Round 1 closed" is not offered a second time under the round it closed');
    /* Baseline and Working Version are the same document until somebody
       proposes something, and both stay on the menu regardless: a selector you
       cannot get back to the live pair from is the trap it exists to prevent. */
    assert.equal(doc('baseline'), doc('working'));
    assert.ok(win.negoVersionByKey(c, 'v1'), 'the key still resolves — nothing was thrown away');
  });

  test('the original is kept automatically, because nobody can recreate it', () => {
    const { win } = buildWorld({});
    const c = contract({ versions: [] });
    if (typeof win.applyOwnerEdit !== 'function') return;
    win.applyOwnerEdit(c, 'A COMPLETELY DIFFERENT AGREEMENT\n1. Scope\nNew wording.');
    const first = (c.versions || [])[0];
    assert.ok(first, 'the wording before the edit must survive it');
    assert.match(first.label, /Original text|As received/);
    assert.equal(first.listed, true, 'and it is offered — everybody needs the original');
  });

  test('a version stored before any of this still appears', () => {
    const { win } = buildWorld({});
    const c = contract({ versions: [{ n: 1, at: '2026-07-01T09:00:00Z', by: 'W',
      label: 'Old snapshot', text: 'AGREEMENT' }] });
    assert.equal(win.listedVersions(c).length, 1,
      'changing how versions are TAKEN must not retire the ones already taken');
  });

  test('taking one asks for a name, and files it under that name', async () => {
    const { win } = buildWorld({});
    const c = contract();
    const asked = [];
    win.promptDialog = async o => { asked.push(o); return 'Before sending to Juno'; };
    const v = await win.takeNamedSnapshot(c);
    assert.equal(asked.length, 1, 'it must ask');
    assert.match(asked[0].label, /Version name/);
    assert.ok(v, 'and save');
    assert.equal(v.label, 'Before sending to Juno');
    assert.equal(v.kind, 'named');
    assert.equal(v.listed, true);
  });

  test('an unnamed one is not saved — better none than one nobody can identify', async () => {
    const { win } = buildWorld({});
    const c = contract();
    win.promptDialog = async () => '   ';
    assert.equal(await win.takeNamedSnapshot(c), null);
    assert.equal((c.versions || []).length, 0);
  });

  test('cancelling saves nothing at all', async () => {
    const { win } = buildWorld({});
    const c = contract();
    win.promptDialog = async () => null;
    assert.equal(await win.takeNamedSnapshot(c), null);
    assert.equal((c.versions || []).length, 0);
  });

  test('and a snapshot of wording that has not moved is refused, with a reason', async () => {
    const { win } = buildWorld({});
    const c = contract();
    win.promptDialog = async () => 'First';
    assert.ok(await win.takeNamedSnapshot(c));
    win.promptDialog = async () => 'Second';
    assert.equal(await win.takeNamedSnapshot(c), null, 'nothing changed between them');
    assert.equal((c.versions || []).length, 1);
    assert.match(win.toastText ? win.toastText() : '', /Nothing has changed|/);
  });
});
